# Generated by Django 5.2.17 on 2026-08-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("country", models.CharField(max_length=100, verbose_name="Mamlakat")),
                (
                    "flag_code",
                    models.CharField(
                        help_text="ISO kod: tr, ae, eg, ge, mv va h.k.",
                        max_length=2,
                        verbose_name="Bayroq kodi",
                    ),
                ),
                ("image_url", models.URLField(max_length=500, verbose_name="Rasm URL")),
                (
                    "price_from",
                    models.PositiveIntegerField(verbose_name="Narx ($, ...dan)"),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="Masalan: 7 kecha / 8 kun",
                        max_length=50,
                        verbose_name="Muddat",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Mashhur belgisi"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
            ],
            options={
                "verbose_name": "Yo'nalish",
                "verbose_name_plural": "Yo'nalishlar",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contact", "So'rov (CTA forma)"),
                            ("flight", "Aviabilet qidiruvi"),
                        ],
                        default="contact",
                        max_length=10,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Aloqa (email/telefon)"
                    ),
                ),
                (
                    "from_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Qayerdan"
                    ),
                ),
                (
                    "to_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Qayerga"
                    ),
                ),
                (
                    "depart_date",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Ketish sanasi"
                    ),
                ),
                (
                    "return_date",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Qaytish sanasi"
                    ),
                ),
                (
                    "passengers",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Yo'lovchilar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Ko'rib chiqildi"),
                ),
            ],
            options={
                "verbose_name": "Murojaat",
                "verbose_name_plural": "Murojaatlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ism-familiya")),
                ("city", models.CharField(max_length=100, verbose_name="Shahar")),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Avatar URL"
                    ),
                ),
                ("text", models.TextField(verbose_name="Fikr matni")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Baho (1-5)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ko'rsatilsin"),
                ),
            ],
            options={
                "verbose_name": "Mijoz fikri",
                "verbose_name_plural": "Mijozlar fikri",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Nomi")),
                ("image_url", models.URLField(max_length=500, verbose_name="Rasm URL")),
                (
                    "duration",
                    models.CharField(
                        help_text="Masalan: 7 kecha / 8 kun",
                        max_length=50,
                        verbose_name="Muddat",
                    ),
                ),
                (
                    "hotel_label",
                    models.CharField(
                        default="5* Hotel", max_length=50, verbose_name="Mehmonxona"
                    ),
                ),
                (
                    "includes",
                    models.CharField(
                        default="Aviabilet + Mehmonxona + Transfer",
                        max_length=200,
                        verbose_name="Nimalar kiradi",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Narx ($)")),
                (
                    "dates",
                    models.CharField(
                        help_text="Masalan: 20 – 27 May",
                        max_length=60,
                        verbose_name="Sanalar",
                    ),
                ),
                (
                    "seats_left",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Qolgan joylar"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=2,
                        verbose_name="Reyting",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
            ],
            options={
                "verbose_name": "Tur",
                "verbose_name_plural": "Turlar",
                "ordering": ["order", "id"],
            },
        ),
    ]
