# Generated by Django 5.2.17 on 2026-08-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Ism"),
        ),
        migrations.AddField(
            model_name="lead",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="core.tour",
                verbose_name="Tur",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="kind",
            field=models.CharField(
                choices=[
                    ("contact", "So'rov (CTA forma)"),
                    ("flight", "Aviabilet qidiruvi"),
                    ("booking", "Tur bron qilish"),
                ],
                default="contact",
                max_length=10,
                verbose_name="Turi",
            ),
        ),
    ]
