# Generated by Django 5.2.17 on 2026-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_lead_name_lead_tour_alter_lead_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="destination",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Mashhur reys",
                "verbose_name_plural": "Mashhur reyslar",
            },
        ),
        migrations.AddField(
            model_name="destination",
            name="from_code",
            field=models.CharField(
                default="TAS", max_length=4, verbose_name="Qayerdan (IATA)"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="to_code",
            field=models.CharField(
                default="",
                help_text="Aeroport kodi, masalan: IST, DXB, AYT",
                max_length=4,
                verbose_name="Qayerga (IATA)",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="duration",
            field=models.CharField(
                help_text="Masalan: 3 soat 40 daqiqa",
                max_length=50,
                verbose_name="Parvoz vaqti",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(
                help_text="Masalan: Istanbul",
                max_length=100,
                verbose_name="Shahar nomi",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="price_from",
            field=models.PositiveIntegerField(
                help_text="Bir tomonlama/borish-qaytish taxminiy narx, $",
                verbose_name="Taxminiy narx ($)",
            ),
        ),
    ]
