# Generated by Django 5.2.17 on 2026-08-14 19:59
# Qo'lda tahrirlangan: "dates" matn maydonini o'chirishdan oldin mavjud
# sayohat sanalarini (agar boshlang'ich namunaviy qiymatlar bo'lsa)
# yangi depart_date/return_date maydonlariga ko'chiradi, shunda saytda
# allaqachon mavjud turlar sanasiz qolib ketmaydi.

import datetime

from django.db import migrations, models

# Boshlang'ich (seed) ma'lumotlardagi "dates" matnlarining aniq mosligi —
# agar admin bu qiymatlarni o'zgartirmagan bo'lsa, ularni avtomatik
# tuzilgan sanalarga aylantiramiz.
_KNOWN_DATES = {
    ("Antalya", "20 – 27 May"): (datetime.date(2026, 5, 20), datetime.date(2026, 5, 27)),
    ("Maldiv", "25 May – 01 Iyun"): (datetime.date(2026, 5, 25), datetime.date(2026, 6, 1)),
    ("Dubay", "22 – 26 May"): (datetime.date(2026, 5, 22), datetime.date(2026, 5, 26)),
    ("Sharm El Sheikh", "18 – 26 May"): (datetime.date(2026, 5, 18), datetime.date(2026, 5, 26)),
    ("Istanbul", "01 – 05 Iyun"): (datetime.date(2026, 6, 1), datetime.date(2026, 6, 5)),
    ("Batumi", "05 – 08 Iyun"): (datetime.date(2026, 6, 5), datetime.date(2026, 6, 8)),
}


def backfill_tour_dates(apps, schema_editor):
    Tour = apps.get_model("core", "Tour")
    for tour in Tour.objects.all():
        match = _KNOWN_DATES.get((tour.title, tour.dates))
        if match:
            tour.depart_date, tour.return_date = match
            tour.save(update_fields=["depart_date", "return_date"])
        # Mos kelmasa (admin qiymatni o'zgartirgan yoki yangi tur qo'shilgan),
        # sanalarni bo'sh qoldiramiz — admin panel orqali qo'lda kiritiladi.


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_destination_options_destination_from_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="depart_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ketish sanasi"),
        ),
        migrations.AddField(
            model_name="tour",
            name="return_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Qaytish sanasi"
            ),
        ),
        migrations.RunPython(backfill_tour_dates, noop_reverse),
        migrations.RemoveField(
            model_name="tour",
            name="dates",
        ),
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Kompyuteringizdan rasm tanlang.",
                null=True,
                upload_to="destinations/",
                verbose_name="Rasm",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="message",
            field=models.TextField(blank=True, verbose_name="Xabar matni"),
        ),
        migrations.AddField(
            model_name="tour",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Kompyuteringizdan rasm tanlang.",
                null=True,
                upload_to="tours/",
                verbose_name="Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Faqat yuqorida rasm yuklanmagan holatda ishlatiladi.",
                max_length=500,
                verbose_name="Rasm URL (zaxira)",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="kind",
            field=models.CharField(
                choices=[
                    ("contact", "So'rov (CTA forma)"),
                    ("flight", "Aviabilet qidiruvi"),
                    ("booking", "Tur bron qilish"),
                    ("message", "Bog'lanish sahifasidagi xabar"),
                ],
                default="contact",
                max_length=10,
                verbose_name="Turi",
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Faqat yuqorida rasm yuklanmagan holatda ishlatiladi.",
                max_length=500,
                verbose_name="Rasm URL (zaxira)",
            ),
        ),
    ]
