# Generated by Django 5.2.17 on 2026-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_tour_dates_destination_image_lead_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_1",
                    models.CharField(
                        default="+998 77 210 54 00",
                        max_length=30,
                        verbose_name="Telefon 1",
                    ),
                ),
                (
                    "phone_2",
                    models.CharField(
                        blank=True,
                        default="+998 77 210 83 71",
                        max_length=30,
                        verbose_name="Telefon 2 (ixtiyoriy)",
                    ),
                ),
                (
                    "email_1",
                    models.EmailField(
                        default="takeavia1@gmail.com",
                        max_length=254,
                        verbose_name="Email 1",
                    ),
                ),
                (
                    "email_2",
                    models.EmailField(
                        blank=True,
                        default="info@takeavia.uz",
                        max_length=254,
                        verbose_name="Email 2 (ixtiyoriy)",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Mirzo Ulug'bek, Parkent ko'chasi, 51",
                        max_length=255,
                        verbose_name="Manzil",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        default="Har kuni, 24/7",
                        max_length=100,
                        verbose_name="Ish vaqti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamalari",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
    ]
