# Generated by Django 5.2.17 on 2026-08-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                default=41.318567,
                help_text="Pastdagi xaritada belgini bosib yoki sudrab aniq joyni tanlang.",
                max_digits=9,
                verbose_name="Xarita — kenglik (latitude)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                default=69.315329,
                max_digits=9,
                verbose_name="Xarita — uzunlik (longitude)",
            ),
        ),
    ]
