# Generated by Django 5.2.17 on 2026-08-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sitesettings_latitude_sitesettings_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(
                blank=True, default="", max_length=300, verbose_name="Facebook havolasi"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Masalan: https://instagram.com/sizning_sahifa",
                max_length=300,
                verbose_name="Instagram havolasi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="telegram_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Masalan: https://t.me/sizning_kanal — bo'sh qoldirilsa, ikonka sahifada ko'rsatilmaydi.",
                max_length=300,
                verbose_name="Telegram havolasi",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(
                blank=True, default="", max_length=300, verbose_name="YouTube havolasi"
            ),
        ),
    ]
