# Generated by Django 5.2.17 on 2026-08-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sitesettings_facebook_url_sitesettings_instagram_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan vaqti"),
        ),
    ]
