# Generated by Django 5.2.17 on 2026-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_tour_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Tur haqida batafsil matn — SEO uchun muhim. Har bir xatboshi yangi qatordan.",
                verbose_name="Tavsif (o'zbekcha)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="description_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bo'sh qoldirilsa, ingliz sahifada o'zbekcha tavsif ko'rsatiladi.",
                verbose_name="Tavsif (inglizcha)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="description_ru",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bo'sh qoldirilsa, rus sahifada o'zbekcha tavsif ko'rsatiladi.",
                verbose_name="Tavsif (ruscha)",
            ),
        ),
    ]
