# Generated by Django 5.2.17 on 2026-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_tour_description_tour_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="text_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bo'sh qoldirilsa, ingliz sahifada o'zbekcha matn ko'rsatiladi.",
                verbose_name="Fikr matni (inglizcha)",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="text_ru",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bo'sh qoldirilsa, rus sahifada o'zbekcha matn ko'rsatiladi.",
                verbose_name="Fikr matni (ruscha)",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="text",
            field=models.TextField(verbose_name="Fikr matni (o'zbekcha)"),
        ),
    ]
