# Generated by Django 5.2.17 on 2026-08-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_testimonial_text_en_testimonial_text_ru_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Kompyuteringizdan rasm tanlang.",
                        null=True,
                        upload_to="tours/gallery/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Faqat yuqorida rasm yuklanmagan holatda ishlatiladi.",
                        max_length=500,
                        verbose_name="Rasm URL (zaxira)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="core.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur galereyasi rasmi",
                "verbose_name_plural": "Tur galereyasi rasmlari (asosiysidan tashqari, 3 tagacha)",
                "ordering": ["order", "id"],
            },
        ),
    ]
